// Configuration file for API keys and settings
// THIS FILE IS AUTO-GENERATED DURING BUILD - DO NOT EDIT MANUALLY
// This file will be generated by the build process using environment variables from Netlify
//
// For local development:
// 1. Copy config.template.js to config.js
// 2. Fill in your API keys
// 3. DO NOT commit config.js with real keys to the repository
//
// For Netlify deployment:
// Set the following environment variables in Netlify dashboard:
// - VISION_API_KEY
// - DEEPSEEK_API_KEY
// - SHEETS_API_KEY
// - SHEET_ID
// - SHEET_NAME (optional, defaults to 'Sites')

const CONFIG = {
    // Google Cloud Vision API Key
    VISION_API_KEY: '',
    
    // DeepSeek API Key
    DEEPSEEK_API_KEY: '',
    
    // Google Sheets API Configuration
    SHEETS_API_KEY: '',
    
    // Google Sheet ID (from the sheet URL)
    SHEET_ID: '',
    
    // Sheet name/tab within the spreadsheet
    SHEET_NAME: 'Sites',
    
    // API endpoints
    VISION_API_URL: 'https://vision.googleapis.com/v1/images:annotate',
    SHEETS_API_URL: 'https://sheets.googleapis.com/v4/spreadsheets',
    DEEPSEEK_API_URL: 'https://api.deepseek.com/v1/chat/completions'
};
